### PR TITLE
Changed to NavigationToolbar2Tk, NavigationToolbar2TkAgg is depreciated

### PR DESCRIPTION
**Pull request by wmoreland**
Matplotlib has depreciated NavigationToolbar2TkAgg in favour of NavigationToolbar2Tk ([apparently just because of the name](https://stackoverflow.com/a/50337997/3297523)) and so running the GUI version of Ashcalc was throwing the error:

`ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg'`

I've replaced all mention of NavigationToolbar2TkAgg with NavigationToolbar2Tk and confirmed it works on both my Linux machine and in Windows 10 with Anaconda.

### CODE REVIEW

**Comment by wmoreland** [comment]
Excuse the typos in the commit message

**Comment by MatthewDaggitt** [comment]
Thanks for the PR, glad to know it's still useful for people! Just tested your changes on my linux machine and it seems to work which is a vast improvement over it not working :smile: 

The only thing to note is that I seem to be having a few resolution problems in that the right hand side of the graph and the error surface panel at the bottom are being cutoff. See image:
image

Are you getting similar problems or is it working for you? No worries though, in all likelihood it's some drift in the Tkinter specification in the last 5 years rather than your changes.

**Comment by wmoreland** [comment]
I'm getting the same issue although I hadn't noticed it before! What I had noticed was these large black patches. They didn't appear in the Windows version though so I thought it must be some issue with themes on my laptop. I see you have the same issue but in a light grey. I'm running i3wm on Arch. 
Arch Linux with i3wm:
2020-01-15-141059_1918x1078_scrot
Windows 10:
2020-01-15-142505_1163x875_scrot
The error surface panel is getting cut off in the Windows version too.

**Comment by wmoreland** [comment]
I tried playing around with the tkinter themes (lines 28 to 39 in gui.py) which affected the sizes of the window components but tkinter should resize things to fit regardless of the theme. As an aside, the tkinter themes installed on my machine are "default", "classic", "alt", and "clam". I am missing three of the themes given on line 30 in gui.py.

"Classic" theme:
2020-01-15-144005_1278x973_scrot
"Clam" theme:
2020-01-15-144033_1278x973_scrot

**Comment by volcan01010** [comment]
> I'm running i3wm on Arch.

Ha!  That's hardcore!

**Comment by volcan01010** [comment]
ashcalc

I can confirm the bug with the current master, and the fix on @wmoreland's branch.  On Ubuntu 18.04 Mate, I get a white background around my images.  Also, the icon in the task bar is a New Zealand flag.

```bash
(ashcalc) js@johnbook:~/GitHub/AshCalc (will-pr) $ python --version
Python 3.6.9
(ashcalc) js@johnbook:~/GitHub/AshCalc (will-pr) $ pip freeze
cycler==0.10.0
kiwisolver==1.1.0
matplotlib==3.1.2
numpy==1.18.1
pkg-resources==0.0.0
pyparsing==2.4.6
python-dateutil==2.8.1
scipy==1.4.1
six==1.14.0
```

**Comment by MatthewDaggitt** [comment]
Okay, thanks for the confirmation. I'll merge this PR in now and then try and sort of the resizing issues some point next week.

**Comment by wmoreland** [comment]
> > I'm running i3wm on Arch.

> Ha! That's hardcore!

@volcan01010 It provides me with literally days of procrastination.

@MatthewDaggitt I'm so happy I've been able to contribute something to AshCalc - genuinely one of my tools of the trade! Thank you for making it!

**Pull request merged**
